//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Application_Setting
    {
        [Key]
        public int ApplicationID { get; set; }
        public int JobID { get; set; }
        public Nullable<System.DateTime> ApplicationDeadline { get; set; }
        public string ApplicationEmail { get; set; }
        public Nullable<bool> ReceiveByEmail { get; set; }

        public int ApplicationSettingsID { get; set; }
        public string Application_Email { get; set; }
        public virtual Job_Detail Job_Details { get; set; }
    }
}
