//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Job_Detail
    {
        [Key]
        public int JobID { get; set; }
        public int CompanyID { get; set; }
        public string JobTitle { get; set; }
        public string JobCategory { get; set; }
        public string Location { get; set; }
        public string Worktype { get; set; }
        public Nullable<decimal> SalaryMin { get; set; }
        public Nullable<decimal> SalaryMax { get; set; }
        public string ExperienceLevel { get; set; }
        public string Jobdescripton { get; set; }
        public string Reqirements { get; set; }
        public string Benefits { get; set; }

        [ForeignKey("JobID")]
        public int Company_ID { get; set; }
        public int ApplicationSettings_ID { get; set; }
        public virtual Application_Setting Application_Settings { get; set; }
        public virtual Company_Information Company_Information { get; set; }
    }
}
